upstreamProjects:
  Mule-runtime/mule/4.7.3-DRY-RUN,
  Mule-runtime/mule-oauth-client/2.2.3-DRY-RUN
mavenSettingsXmlId: mule-runtime-maven-settings-MuleSettings
projectType: runtime
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
  jdk11:
    testJdkTool: OPEN-JDK11
